import mongoose from 'mongoose';

const ChatRoomSchema = mongoose.Schema(
  {
    // _id will be autogenerated by MongoDB and is used to identify the chat room
    // usernames of the participants in the chat room (should be always 2 as group chats are separate models)
    members: Array,
  },
  { timestamps: true },
);

const ChatRoom = mongoose.model('ChatRoom', ChatRoomSchema);

export default ChatRoom;
